graph LR
  Create_pool("Create <br>Rules Engines <br>Pool")
  Acquire_engine(Acquire <br>Rules <br>Engine)
  Assert_facts[Assert <br>facts]
  Reason[Reason]
  Collect_fact_results[Collect <br>Fact <br>Results]
  Release_engine(Release <br>Rules <br>Engine)
  State_store((State Store))


  style Create_pool fill:#99f,stroke:#000,stroke-width:2px
  style Acquire_engine fill:#99f,stroke:#000,stroke-width:2px
  style Release_engine fill:#99f,stroke:#000,stroke-width:2px

  style Assert_facts fill:#9f9,stroke:#000,stroke-width:2px
  style Reason fill:#9f9,stroke:#000,stroke-width:2px
  style Collect_fact_results fill:#9f9,stroke:#000,stroke-width:2px

  style State_store fill:#dcc,stroke:#000,stroke-width:1px,stroke-dasharray: 5, 5

  Create_pool --> Acquire_engine
  Acquire_engine --> Assert_facts
  Assert_facts --> Reason
  Reason --> Collect_fact_results
  Collect_fact_results --> Release_engine

  State_store -.-> Acquire_engine
  Release_engine -.-> State_store
